const DEMO={
 ITUB4:{name:'Itaú Unibanco',sector:'Bancos',price:38.42,dy:6.8,pe:8.7,score:82,lpa:4.42,vpa:28.70,payout:58,cagr:11.2,history:[2.9,3.3,3.7,4.0,4.2,4.42],years:[2021,2022,2023,2024,2025,2026],div:[1.65,1.91,2.08,2.28,2.51]},
 BBAS3:{name:'Banco do Brasil',sector:'Bancos',price:24.10,dy:9.1,pe:5.1,score:88,lpa:4.73,vpa:28.90,payout:46,cagr:13.8,history:[3.1,3.5,3.8,4.1,4.5,4.73],years:[2021,2022,2023,2024,2025,2026],div:[1.10,1.25,1.80,2.10,2.20]}
};
const API_BASE=new URLSearchParams(location.search).get('api')||localStorage.getItem('DD_API_BASE')||'';
function money(v){return v==null?'—':Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});} function pct(v){return v==null?'—':Number(v).toLocaleString('pt-BR',{maximumFractionDigits:1})+'%';}
function setText(id,v){const e=document.querySelector('#'+id);if(e)e.textContent=v;}
function normalizeApi(x){const m=x.latest_metrics||{};const q=x.latest_quote||{};const hist=(x.financial_history||[]).filter(r=>r.net_income!=null);return {name:x.company_name,sector:x.sector||'—',price:m.close??q.close,dy:m.dividend_yield!=null?m.dividend_yield*100:null,pe:m.pe_current,score:m.quality_score,lpa:m.lpa,vpa:m.vpa,payout:m.payout_expected!=null?m.payout_expected*100:null,cagr:m.earnings_cagr_5y!=null?m.earnings_cagr_5y*100:null,history:hist.slice().reverse().map(r=>r.attributable_net_income??r.net_income),years:hist.slice().reverse().map(r=>new Date(r.reference_period).getFullYear()),div:(x.corporate_actions||[]).filter(a=>a.adjusted_amount_per_share!=null).slice(0,8).reverse().map(a=>Number(a.adjusted_amount_per_share)),gate:x.quality_gate};}
function render(ticker,d,source){document.title=`Doutor dos Dividendos — ${ticker}`;setText('company',`${ticker} — ${d.name}`);setText('sector',`${d.sector} • ${source}`);setText('price',money(d.price));setText('dy',pct(d.dy));setText('pe',d.pe==null?'—':Number(d.pe).toLocaleString('pt-BR')+'x');setText('score',d.score==null?'—':Math.round(d.score)+'/100');setText('lpa',money(d.lpa));setText('vpa',money(d.vpa));setText('payout',pct(d.payout));setText('cagr',pct(d.cagr));
 const hist=d.history||[];const years=d.years||[];const max=Math.max(...hist,1);document.querySelector('#bars').innerHTML=hist.length?hist.map((v,i)=>`<div class="bar" style="height:${Math.max(8,v/max*82)}%"><i>${years[i]||''}</i></div>`).join(''):'<span>Histórico indisponível</span>';
 document.querySelector('#divrows').innerHTML=(d.div||[]).map((v,i)=>`<tr><td>${i+1}</td><td>${money(v)}</td><td>—</td></tr>`).join('')||'<tr><td colspan="3">Eventos de proventos ainda não disponíveis</td></tr>';
 const gate=d.gate||{status:'DEMO',score:0};const badge=document.querySelector('.badge');badge.textContent=`Quality Gate: ${gate.status}`;document.querySelector('.quality .dot').className='dot '+String(gate.status).toLowerCase();document.querySelector('#methodNote').textContent=source==='API real'?'Dados carregados da API. O ranking somente deve considerar empresas com ranking_eligible=true após a migração do Quality Gate.':'Modo demonstrativo: conecte a API para substituir os valores de exemplo.';
}
async function load(ticker){if(API_BASE){try{const r=await fetch(`${API_BASE.replace(/\/$/,'')}/api/ativos/${encodeURIComponent(ticker)}`);if(r.ok){render(ticker,normalizeApi(await r.json()),'API real');return;}}catch(e){console.warn('API indisponível',e)}}render(ticker,DEMO[ticker]||DEMO.ITUB4,'dados demonstrativos');}
const ticker=(new URLSearchParams(location.search).get('ticker')||'ITUB4').toUpperCase();load(ticker);
